#!/bin/bash

# Get video index
VIDEO_INDEX=${1:-0}

# Get the current framerate
echo "Fetching the current framerate for /dev/video${VIDEO_INDEX}"
v4l2-ctl --device /dev/video${VIDEO_INDEX} --get-parm
